import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Interior Designing and Interior Decoration Services',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Residential, Commercial, Corporate and Industrial Interior Planning',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Vastu Consultancy and Space Planning Services',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Software Design, Development, Maintenance and Customization',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'Website Design, Development and Maintenance',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Information Technology (IT) Consultancy Services',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Digital Transformation and Business Automation Solutions',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 8,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Mobile Application Development',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 9,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Cloud-Based Solutions and IT Support Services',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
    {
    id: 10,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Digital Marketing and Online Business Solutions',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
    {
    id: 11,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Technology Consulting and Software Implementation',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
